Repository FalloutStudios/Axis, pull requests merged in 2021-12, with the labels that each got.

#39 1.5.0
  index.js
  modules/axis.js
  package-lock.json
  package.json
  scripts/builders/index.js
  scripts/builders/interactionCommandBuilder.js
  scripts/builders/messageCommandBuilder.js
  scripts/config/config.js
  scripts/config/index.js
  scripts/config/language.js
  scripts/dataTypeValidator/index.js
  scripts/loadScripts.js
  scripts/makeConfig.js
  scripts/registerInteractionCommands.js
  scripts/safeActions/index.js
  scripts/safeActions/safeInteract.js
  scripts/safeActions/safeMessage.js
  scripts/version.js
Labels: Priority: High, Type: Enhancement, Type: New Feature

#61 Fixed krazy yml format by Ghex
  modules/axis.js
Labels: Type: Enhancement

#63 Update discord-api-types to `@0.26.0` bc Ghex's ass lazy af
  package-lock.json
  package.json
Labels: Type: Enhancement

#64 Add node `16.6.0` to workflow bcoz u seems krazy
  .github/workflows/codeql-analysis.yml
  .github/workflows/node.js.yml
Labels: Priority: Low, Type: Enhancement
